[2025-05-08T13:52:32.028+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:51:56.586331+00:00 [queued]>
[2025-05-08T13:52:32.052+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:51:56.586331+00:00 [queued]>
[2025-05-08T13:52:32.053+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-08T13:52:32.089+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_gold_data> on 2025-05-08 13:51:56.586331+00:00
[2025-05-08T13:52:32.104+0000] {standard_task_runner.py:57} INFO - Started process 4036 to run task
[2025-05-08T13:52:32.109+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'transform_gold_data', 'manual__2025-05-08T13:51:56.586331+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpndk90ois']
[2025-05-08T13:52:32.114+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask transform_gold_data
[2025-05-08T13:52:32.216+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:51:56.586331+00:00 [running]> on host 223a2d167166
[2025-05-08T13:52:32.428+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='transform_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T13:51:56.586331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T13:51:56.586331+00:00'
[2025-05-08T13:52:32.431+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/gold_prices/2025-05-08.csv'.
[2025-05-08T13:52:32.511+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/fed_rates/2025-05-08.csv'.
[2025-05-08T13:52:32.541+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/sp500/2025-05-08.csv'.
[2025-05-08T13:52:32.646+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform.py", line 76, in transform_gold_data
    premier_prix = merged_df["prix_or"].iloc[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
[2025-05-08T13:52:32.671+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_pipeline, task_id=transform_gold_data, execution_date=20250508T135156, start_date=20250508T135232, end_date=20250508T135232
[2025-05-08T13:52:32.707+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task transform_gold_data (single positional indexer is out-of-bounds; 4036)
[2025-05-08T13:52:32.770+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-08T13:52:32.826+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
