[2025-05-20T13:54:36.105+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_spark.run_kafka_script manual__2025-05-20T13:54:34.542271+00:00 [queued]>
[2025-05-20T13:54:36.117+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_spark.run_kafka_script manual__2025-05-20T13:54:34.542271+00:00 [queued]>
[2025-05-20T13:54:36.117+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T13:54:36.139+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_kafka_script> on 2025-05-20 13:54:34.542271+00:00
[2025-05-20T13:54:36.147+0000] {standard_task_runner.py:57} INFO - Started process 1540 to run task
[2025-05-20T13:54:36.168+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'start_kafka_spark', 'run_kafka_script', 'manual__2025-05-20T13:54:34.542271+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/streaming_lance.py', '--cfg-path', '/tmp/tmpldbre1sy']
[2025-05-20T13:54:36.173+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask run_kafka_script
[2025-05-20T13:54:36.317+0000] {task_command.py:415} INFO - Running <TaskInstance: start_kafka_spark.run_kafka_script manual__2025-05-20T13:54:34.542271+00:00 [running]> on host 341131c8572d
[2025-05-20T13:54:36.448+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='start_kafka_spark' AIRFLOW_CTX_TASK_ID='run_kafka_script' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T13:54:34.542271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T13:54:34.542271+00:00'
[2025-05-20T13:54:36.452+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T13:54:36.454+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec gold_price_project-kafka-1 python3 /scripts/gold_price.py &\n        ']
[2025-05-20T13:54:36.466+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T13:56:27.052+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-20T13:56:27.056+0000] {process_utils.py:131} INFO - Sending 15 to group 1540. PIDs of all processes in the group: [1549, 1540]
[2025-05-20T13:56:27.057+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1540
[2025-05-20T13:56:27.058+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-20T13:56:27.059+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-20T13:56:27.111+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1540, status='terminated', exitcode=0, started='13:54:35') (1540) terminated with exit code 0
[2025-05-20T13:56:27.112+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1549, status='terminated', started='13:54:35') (1549) terminated with exit code None
