[2025-05-17T14:50:55.730+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:50:55.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:50:55.732+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:50:55.732+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:51:00.760+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:51:00.759+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:51:05.266+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:51:05.254+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:51:05.268+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:51:05.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 9.574 seconds
[2025-05-17T14:51:35.904+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:51:35.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:51:35.908+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:51:35.908+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:51:39.311+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:51:39.310+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:51:42.587+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:51:42.572+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:51:42.590+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:51:42.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 6.727 seconds
[2025-05-17T14:52:13.118+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:13.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:52:13.122+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:13.121+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:14.123+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:14.122+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:52:16.888+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:16.873+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:52:16.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:16.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.813 seconds
[2025-05-17T14:52:47.969+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:47.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:52:47.973+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:47.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:49.060+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:49.059+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:52:51.248+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:52:51.096+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:52:51.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:52:51.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.309 seconds
[2025-05-17T14:53:21.577+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:21.578+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:53:21.581+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:21.580+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:22.597+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:22.595+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:53:24.681+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:24.668+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:53:24.683+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:24.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.133 seconds
[2025-05-17T14:53:55.436+0000] {processor.py:157} INFO - Started process (PID=354) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:55.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:53:55.439+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:55.438+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:56.901+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:56.899+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:53:59.838+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:53:59.827+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:53:59.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:53:59.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 4.430 seconds
[2025-05-17T14:54:30.614+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:54:30.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:54:30.617+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:54:30.617+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:54:31.788+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:54:31.787+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:54:34.643+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:54:34.629+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:54:34.646+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:54:34.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 4.060 seconds
[2025-05-17T14:55:05.545+0000] {processor.py:157} INFO - Started process (PID=422) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:05.547+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:55:05.548+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:05.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:06.487+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:06.487+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:55:09.117+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:09.102+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:55:09.119+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:09.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.603 seconds
[2025-05-17T14:55:39.499+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:39.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:55:39.502+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:39.501+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:41.626+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:41.626+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:55:44.553+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:55:44.536+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:55:44.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:55:44.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.997 seconds
[2025-05-17T14:56:14.782+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:14.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:56:14.787+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:14.787+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:15.805+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:15.804+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:56:17.968+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:17.950+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:56:17.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:18.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.230 seconds
[2025-05-17T14:56:48.216+0000] {processor.py:157} INFO - Started process (PID=533) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:48.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:56:48.223+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:48.222+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:50.144+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:50.143+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:56:52.616+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:56:52.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:56:52.619+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:56:52.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 4.465 seconds
[2025-05-17T14:57:23.098+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:57:23.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:57:23.100+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:57:23.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:57:24.065+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:57:24.064+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:57:26.099+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:57:26.083+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:57:26.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:57:26.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.030 seconds
[2025-05-17T14:57:56.510+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:57:56.511+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:57:56.512+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:57:56.512+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:57:57.829+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:57:57.828+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:58:00.454+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:00.440+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 22, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', '-u', 'root', 'namenode', 'hdfs', 'dfs', '-chmod', '-R', '777', '/gold_datalake/raw/gold_prices']' returned non-zero exit status 1.
[2025-05-17T14:58:00.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:58:00.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 3.985 seconds
[2025-05-17T14:58:31.103+0000] {processor.py:157} INFO - Started process (PID=634) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:58:31.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:58:31.107+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:31.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:58:32.590+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:32.589+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:58:56.658+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:56.657+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:58:56.946+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T14:58:57.128+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.128+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:58:57.141+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:58:57.410+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.410+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T14:58:57.427+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.427+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T14:58:57.437+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.436+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T14:58:57.439+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.438+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipeline' as access control is unset.
[2025-05-17T14:58:57.440+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.440+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T14:58:57.459+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.458+0000] {dag.py:2937} INFO - Creating ORM DAG for gold_pipeline
[2025-05-17T14:58:57.475+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:58:57.475+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T14:58:57.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 25.710 seconds
[2025-05-17T14:59:27.712+0000] {processor.py:157} INFO - Started process (PID=761) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T14:59:27.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T14:59:27.714+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:27.714+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T14:59:28.918+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:28.917+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:59:49.588+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:49.588+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:59:49.798+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T14:59:50.010+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:50.010+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T14:59:50.031+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T14:59:50.068+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:50.068+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T14:59:50.093+0000] {logging_mixin.py:151} INFO - [2025-05-17T14:59:50.093+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T14:59:50.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.411 seconds
[2025-05-17T15:00:20.613+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:00:20.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:00:20.618+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:20.617+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:00:21.547+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:21.546+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:00:42.242+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:42.241+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:00:42.416+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:00:42.526+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:42.526+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:00:42.541+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:00:42.589+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:42.586+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:00:42.637+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:00:42.637+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:00:42.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.328 seconds
[2025-05-17T15:01:13.070+0000] {processor.py:157} INFO - Started process (PID=996) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:01:13.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:01:13.079+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:13.079+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:01:14.266+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:14.265+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:01:36.739+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:36.738+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:01:37.229+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:01:37.398+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:37.396+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:01:37.419+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:01:37.469+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:37.468+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:01:37.512+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:01:37.512+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:01:37.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.774 seconds
[2025-05-17T15:02:08.136+0000] {processor.py:157} INFO - Started process (PID=1107) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:02:08.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:02:08.151+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:02:08.149+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:02:09.800+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:02:09.800+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:07:55.183+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:07:55.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:07:55.198+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:07:55.197+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:08:01.386+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:08:01.377+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:08:28.005+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:08:28.003+0000] {timeout.py:68} ERROR - Process timed out, PID: 170
[2025-05-17T15:08:28.027+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:08:28.011+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 170
[2025-05-17T15:08:28.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:08:28.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.213 seconds
[2025-05-17T15:08:59.540+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:08:59.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:08:59.546+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:08:59.545+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:09:00.836+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:00.836+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:09:22.623+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:22.623+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:09:23.660+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:09:24.660+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:24.653+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:09:24.688+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:09:24.985+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:24.985+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T15:09:25.046+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.046+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T15:09:25.091+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.091+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-17T15:09:25.093+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.092+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipeline' as access control is unset.
[2025-05-17T15:09:25.095+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.094+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:09:25.130+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.129+0000] {dag.py:2937} INFO - Creating ORM DAG for gold_pipeline
[2025-05-17T15:09:25.179+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:25.178+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:09:25.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 25.680 seconds
[2025-05-17T15:09:56.010+0000] {processor.py:157} INFO - Started process (PID=384) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:09:56.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:09:56.014+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:56.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:09:57.172+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:09:57.171+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:10:20.534+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:20.533+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:10:20.860+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:10:21.049+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:21.048+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:10:21.080+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:10:21.136+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:21.134+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:10:21.190+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:21.190+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:10:21.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 24.061 seconds
[2025-05-17T15:10:51.441+0000] {processor.py:157} INFO - Started process (PID=589) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:10:51.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:10:51.444+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:51.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:10:53.708+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:10:53.708+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:11:22.131+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:22.130+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:11:22.494+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:11:22.653+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:22.653+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:11:22.663+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:11:22.692+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:22.691+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:11:22.726+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:22.726+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:11:22.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 28.607 seconds
[2025-05-17T15:11:53.277+0000] {processor.py:157} INFO - Started process (PID=897) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:11:53.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:11:53.282+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:53.281+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:11:54.890+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:11:54.889+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:12:19.465+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:19.465+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:12:19.706+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:12:19.841+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:19.841+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:12:19.851+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:12:19.884+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:19.884+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:12:19.914+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:19.913+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:12:19.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 25.534 seconds
[2025-05-17T15:12:50.088+0000] {processor.py:157} INFO - Started process (PID=1004) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:12:50.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:12:50.092+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:50.091+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:12:51.617+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:12:51.616+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:13:14.221+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:14.221+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:13:14.446+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:13:14.539+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:14.539+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:13:14.555+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:13:14.595+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:14.594+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:13:14.641+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:14.641+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:13:14.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.861 seconds
[2025-05-17T15:13:46.600+0000] {processor.py:157} INFO - Started process (PID=1109) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:13:46.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:13:46.604+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:46.604+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:13:47.914+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:13:47.913+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:06.624+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:06.624+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:06.793+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:14:06.895+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:06.894+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:06.902+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:14:06.925+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:06.924+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:14:06.945+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:06.945+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:14:06.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.375 seconds
[2025-05-17T15:14:37.115+0000] {processor.py:157} INFO - Started process (PID=1217) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:14:37.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:14:37.119+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:37.119+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:14:38.106+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:38.106+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:56.780+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:56.779+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:57.034+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:14:57.285+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:57.284+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:14:57.301+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:14:57.330+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:57.330+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:14:57.355+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:14:57.355+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:14:57.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.336 seconds
[2025-05-17T15:15:27.606+0000] {processor.py:157} INFO - Started process (PID=1329) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:15:27.608+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:15:27.609+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:27.609+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:15:28.554+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:28.554+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:15:49.023+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:49.022+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:15:49.280+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:15:49.365+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:49.365+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:15:49.373+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:15:49.403+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:49.402+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:15:49.433+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:15:49.432+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:15:49.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.856 seconds
[2025-05-17T15:16:20.131+0000] {processor.py:157} INFO - Started process (PID=1428) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:16:20.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:16:20.134+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:20.133+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:16:23.759+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:23.759+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:16:42.156+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:42.155+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:16:42.372+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:16:42.454+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:42.453+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:16:42.464+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:16:42.495+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:42.494+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:16:42.530+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:16:42.530+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:16:42.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.707 seconds
[2025-05-17T15:17:12.901+0000] {processor.py:157} INFO - Started process (PID=1539) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:17:12.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:17:12.903+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:12.903+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:17:14.030+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:14.030+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:17:36.571+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:36.570+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:17:36.790+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:17:36.902+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:36.901+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:17:36.910+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:17:36.940+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:36.940+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:17:36.977+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:17:36.977+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:17:37.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.385 seconds
[2025-05-17T15:18:07.190+0000] {processor.py:157} INFO - Started process (PID=1649) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:18:07.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:18:07.199+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:07.198+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:18:08.936+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:08.935+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:18:27.731+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:27.731+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:18:27.990+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:18:28.101+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:28.101+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:18:28.108+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:18:28.138+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:28.137+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:18:28.169+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:28.169+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:18:28.190+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.006 seconds
[2025-05-17T15:18:58.856+0000] {processor.py:157} INFO - Started process (PID=1749) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:18:58.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:18:58.867+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:18:58.865+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:19:00.154+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:00.153+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:19:20.419+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:20.418+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:19:20.681+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:19:20.817+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:20.816+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:19:20.830+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:19:20.874+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:20.873+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:19:20.931+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:20.931+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:19:20.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.209 seconds
[2025-05-17T15:19:51.318+0000] {processor.py:157} INFO - Started process (PID=1858) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:19:51.319+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:19:51.321+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:51.320+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:19:52.158+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:19:52.158+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:20:12.183+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:12.181+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:20:12.423+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:20:12.538+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:12.538+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:20:12.547+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:20:12.576+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:12.575+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:20:12.599+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:12.599+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:20:12.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.582 seconds
[2025-05-17T15:20:43.338+0000] {processor.py:157} INFO - Started process (PID=1967) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:20:43.340+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:20:43.341+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:43.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:20:44.157+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:20:44.156+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:02.867+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:02.867+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:03.488+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:21:03.731+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:03.731+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:03.741+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:21:03.763+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:03.763+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:21:03.792+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:03.792+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:21:03.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.477 seconds
[2025-05-17T15:21:34.053+0000] {processor.py:157} INFO - Started process (PID=2071) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:21:34.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:21:34.055+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:34.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:21:35.112+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:35.111+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:57.011+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:57.010+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:57.241+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:21:57.376+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:57.376+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:21:57.387+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:21:57.427+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:57.426+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:21:57.467+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:21:57.466+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:21:57.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.746 seconds
[2025-05-17T15:22:28.041+0000] {processor.py:157} INFO - Started process (PID=2183) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:22:28.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:22:28.044+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:28.044+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:22:30.038+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:30.038+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:22:51.560+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:51.559+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:22:51.781+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:22:51.872+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:51.872+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:22:51.881+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:22:51.907+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:51.907+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:22:51.926+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:22:51.926+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:22:51.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.202 seconds
[2025-05-17T15:23:22.081+0000] {processor.py:157} INFO - Started process (PID=2293) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:23:22.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:23:22.091+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:23:22.090+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:23:24.047+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:23:24.045+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:23:54.831+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:23:54.829+0000] {timeout.py:68} ERROR - Process timed out, PID: 2293
[2025-05-17T15:23:54.856+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:23:54.837+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2293
[2025-05-17T15:23:54.857+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:23:54.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.124 seconds
[2025-05-17T15:24:25.260+0000] {processor.py:157} INFO - Started process (PID=2404) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:24:25.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:24:25.262+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:25.262+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:24:26.273+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:26.272+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:24:46.861+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:46.860+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:24:47.079+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:24:47.301+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:47.301+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:24:47.312+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:24:47.501+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:47.501+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipeline' as access control is unset.
[2025-05-17T15:24:47.504+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:47.502+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:24:47.545+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:24:47.545+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:24:47.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.314 seconds
[2025-05-17T15:25:18.054+0000] {processor.py:157} INFO - Started process (PID=2501) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:25:18.056+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:25:18.057+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:18.057+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:25:19.507+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:19.507+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:25:40.969+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:40.969+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:25:41.270+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:25:41.370+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:41.370+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:25:41.382+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:25:41.414+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:41.414+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:25:41.434+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:25:41.434+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:25:41.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.681 seconds
[2025-05-17T15:26:11.684+0000] {processor.py:157} INFO - Started process (PID=2611) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:26:11.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:26:11.688+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:11.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:26:12.591+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:12.590+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:26:32.662+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:32.662+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:26:33.049+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:26:33.327+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:33.327+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:26:33.360+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:26:33.424+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:33.421+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:26:33.482+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:26:33.481+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:26:33.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.181 seconds
[2025-05-17T15:27:04.684+0000] {processor.py:157} INFO - Started process (PID=2712) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:27:04.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:27:04.688+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:04.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:27:05.985+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:05.984+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:27:24.224+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:24.223+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:27:24.434+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:27:24.539+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:24.539+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:27:24.548+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:27:24.572+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:24.572+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:27:24.599+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:24.599+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:27:24.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.953 seconds
[2025-05-17T15:27:54.781+0000] {processor.py:157} INFO - Started process (PID=2821) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:27:54.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:27:54.786+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:54.786+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:27:55.730+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:27:55.729+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:28:13.452+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:13.451+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:28:13.707+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:28:13.867+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:13.866+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:28:13.881+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:28:13.922+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:13.921+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:28:13.958+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:13.957+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:28:13.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.559 seconds
[2025-05-17T15:28:44.464+0000] {processor.py:157} INFO - Started process (PID=2931) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:28:44.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:28:44.468+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:44.467+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:28:45.525+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:28:45.524+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:07.309+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:07.308+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:07.648+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:29:07.752+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:07.752+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:07.763+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:29:07.790+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:07.789+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:29:07.815+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:07.815+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:29:07.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 23.387 seconds
[2025-05-17T15:29:38.186+0000] {processor.py:157} INFO - Started process (PID=3031) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:29:38.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:29:38.190+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:38.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:29:39.202+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:39.201+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:58.018+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:58.017+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:58.179+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:29:58.274+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:58.273+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:29:58.289+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:29:58.318+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:58.317+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:29:58.344+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:29:58.343+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:29:58.367+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 17.463 seconds
[2025-05-17T15:30:28.510+0000] {processor.py:157} INFO - Started process (PID=3143) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:30:28.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:30:28.513+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:28.513+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:30:29.672+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:29.672+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:30:52.137+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:52.136+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:30:52.378+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-17T15:30:52.507+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:52.507+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-17T15:30:52.515+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipeline']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-17T15:30:52.539+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:52.539+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-17T15:30:52.570+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:30:52.570+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipeline to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-17T15:30:52.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.370 seconds
[2025-05-17T15:31:23.136+0000] {processor.py:157} INFO - Started process (PID=3255) to work on /opt/airflow/dags/pipeline.py
[2025-05-17T15:31:23.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-17T15:31:23.139+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:31:23.138+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-17T15:31:24.115+0000] {logging_mixin.py:151} INFO - [2025-05-17T15:31:24.115+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
