[2025-05-20T10:11:00.335+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:11:00.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:11:00.352+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:11:00.351+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:11:08.008+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:11:08.006+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:11:30.397+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:11:30.389+0000] {timeout.py:68} ERROR - Process timed out, PID: 166
[2025-05-20T10:11:30.465+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:11:30.402+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 166
[2025-05-20T10:11:30.468+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:11:30.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.315 seconds
[2025-05-20T10:12:01.154+0000] {processor.py:157} INFO - Started process (PID=248) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:12:01.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:12:01.159+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:01.158+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:12:02.531+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:02.530+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:12:27.915+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:27.914+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:12:28.598+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:12:29.254+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.253+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:12:29.285+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:12:29.506+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.506+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:12:29.520+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.520+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:12:29.529+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.529+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:12:29.531+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.530+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:12:29.534+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.532+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:12:29.566+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.564+0000] {dag.py:2937} INFO - Creating ORM DAG for gold_pipelines
[2025-05-20T10:12:29.609+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:12:29.609+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:12:29.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 28.538 seconds
[2025-05-20T10:13:00.043+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:13:00.071+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:13:00.130+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:13:00.105+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:13:06.326+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:13:06.325+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:13:30.210+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:13:30.203+0000] {timeout.py:68} ERROR - Process timed out, PID: 363
[2025-05-20T10:13:30.265+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:13:30.218+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 363
[2025-05-20T10:13:30.273+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:13:30.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.543 seconds
[2025-05-20T10:14:01.060+0000] {processor.py:157} INFO - Started process (PID=684) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:14:01.069+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:14:01.089+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:14:01.088+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:14:05.555+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:14:05.554+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:14:31.191+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:14:31.186+0000] {timeout.py:68} ERROR - Process timed out, PID: 684
[2025-05-20T10:14:31.345+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:14:31.220+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 684
[2025-05-20T10:14:31.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:14:31.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.435 seconds
[2025-05-20T10:15:02.106+0000] {processor.py:157} INFO - Started process (PID=1022) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:15:02.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:15:02.111+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:02.110+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:15:05.188+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:05.187+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:15:31.278+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:31.277+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:15:31.614+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:15:31.821+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:31.821+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:15:31.831+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:15:32.046+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:32.045+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:15:32.050+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:32.049+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:15:32.082+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:15:32.082+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:15:32.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.056 seconds
[2025-05-20T10:16:02.954+0000] {processor.py:157} INFO - Started process (PID=1248) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:16:02.964+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:16:02.970+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:16:02.970+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:16:06.094+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:16:06.093+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:16:32.987+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:16:32.981+0000] {timeout.py:68} ERROR - Process timed out, PID: 1248
[2025-05-20T10:16:33.016+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:16:32.993+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 1248
[2025-05-20T10:16:33.021+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:16:33.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.203 seconds
[2025-05-20T10:17:03.803+0000] {processor.py:157} INFO - Started process (PID=1725) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:17:03.805+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:17:03.807+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:17:03.806+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:17:06.085+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:17:06.084+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:17:33.791+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:17:33.785+0000] {timeout.py:68} ERROR - Process timed out, PID: 1725
[2025-05-20T10:17:33.825+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:17:33.805+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 1725
[2025-05-20T10:17:33.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:17:33.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.132 seconds
[2025-05-20T10:18:04.909+0000] {processor.py:157} INFO - Started process (PID=2070) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:18:04.910+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:18:04.912+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:04.912+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:18:06.217+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:06.216+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:18:26.498+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:26.498+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:18:26.709+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:18:26.835+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:26.835+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:18:26.843+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:18:26.960+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:26.959+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:18:26.962+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:26.961+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:18:26.985+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:26.985+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:18:27.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.144 seconds
[2025-05-20T10:18:57.931+0000] {processor.py:157} INFO - Started process (PID=2296) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:18:57.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:18:57.935+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:57.935+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:18:59.850+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:18:59.849+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:19:27.913+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:19:27.907+0000] {timeout.py:68} ERROR - Process timed out, PID: 2296
[2025-05-20T10:19:27.955+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:19:27.925+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2296
[2025-05-20T10:19:27.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:19:28.022+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.145 seconds
[2025-05-20T10:19:58.357+0000] {processor.py:157} INFO - Started process (PID=2705) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:19:58.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:19:58.379+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:19:58.378+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:20:01.836+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:20:01.835+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:20:28.381+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:20:28.378+0000] {timeout.py:68} ERROR - Process timed out, PID: 2705
[2025-05-20T10:20:28.401+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:20:28.387+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2705
[2025-05-20T10:20:28.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:20:28.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.132 seconds
[2025-05-20T10:21:09.373+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:21:09.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:21:09.379+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:09.379+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:21:10.954+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:10.953+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:21:30.791+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:30.791+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:21:31.031+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:21:31.287+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:31.287+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:21:31.295+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:21:31.408+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:31.408+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:21:31.410+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:31.409+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:21:31.434+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:21:31.434+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:21:31.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.101 seconds
[2025-05-20T10:22:01.912+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:22:01.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:22:01.915+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:22:01.915+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:22:02.954+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:22:02.953+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:22:31.885+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:22:31.878+0000] {timeout.py:68} ERROR - Process timed out, PID: 276
[2025-05-20T10:22:31.954+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:22:31.903+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 276
[2025-05-20T10:22:31.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:22:32.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.197 seconds
[2025-05-20T10:23:02.356+0000] {processor.py:157} INFO - Started process (PID=672) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:23:02.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:23:02.363+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:23:02.362+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:23:05.569+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:23:05.568+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:23:32.411+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:23:32.406+0000] {timeout.py:68} ERROR - Process timed out, PID: 672
[2025-05-20T10:23:32.433+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:23:32.417+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 672
[2025-05-20T10:23:32.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:23:32.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.166 seconds
[2025-05-20T10:24:03.312+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:03.319+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:24:03.321+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:24:03.321+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:04.680+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:24:04.670+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:24:04.684+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:04.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 1.430 seconds
[2025-05-20T10:24:35.010+0000] {processor.py:157} INFO - Started process (PID=1185) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:35.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:24:35.013+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:24:35.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:35.614+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:24:35.602+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:24:35.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:24:35.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.636 seconds
[2025-05-20T10:25:05.990+0000] {processor.py:157} INFO - Started process (PID=1201) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:05.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:25:05.992+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:25:05.992+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:06.457+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:25:06.447+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:25:06.460+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:06.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.492 seconds
[2025-05-20T10:25:36.801+0000] {processor.py:157} INFO - Started process (PID=1217) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:36.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:25:36.805+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:25:36.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:37.569+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:25:37.550+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:25:37.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:25:37.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.830 seconds
[2025-05-20T10:26:07.821+0000] {processor.py:157} INFO - Started process (PID=1233) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:07.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:26:07.823+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:26:07.823+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:08.197+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:26:08.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:26:08.199+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:08.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.403 seconds
[2025-05-20T10:26:38.285+0000] {processor.py:157} INFO - Started process (PID=1249) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:38.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:26:38.287+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:26:38.287+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:38.626+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:26:38.618+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:26:38.628+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:26:38.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.371 seconds
[2025-05-20T10:27:08.953+0000] {processor.py:157} INFO - Started process (PID=1265) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:08.954+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:27:08.955+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:27:08.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:09.308+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:27:09.297+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:27:09.310+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:09.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.383 seconds
[2025-05-20T10:27:39.742+0000] {processor.py:157} INFO - Started process (PID=1281) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:39.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:27:39.744+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:27:39.744+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:40.073+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:27:40.062+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:27:40.074+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:27:40.095+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.357 seconds
[2025-05-20T10:28:04.392+0000] {processor.py:157} INFO - Started process (PID=1297) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:04.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:28:04.395+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:28:04.395+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:04.770+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:28:04.759+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:28:04.773+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:04.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.411 seconds
[2025-05-20T10:28:08.833+0000] {processor.py:157} INFO - Started process (PID=1303) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:08.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:28:08.836+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:28:08.836+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:09.352+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:28:09.341+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:28:09.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:28:09.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.560 seconds
[2025-05-20T10:29:24.485+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:24.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:29:24.489+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:29:24.488+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:27.314+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:29:27.298+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:29:27.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:27.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 2.874 seconds
[2025-05-20T10:29:58.207+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:58.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:29:58.211+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:29:58.211+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:59.045+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:29:59.012+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:29:59.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:29:59.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.890 seconds
[2025-05-20T10:30:29.299+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:30:29.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:30:29.302+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:30:29.301+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:30:29.990+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:30:29.982+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:30:29.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:30:30.022+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.727 seconds
[2025-05-20T10:31:00.603+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:00.604+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:31:00.605+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:31:00.605+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:01.491+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:31:01.481+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 8, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:31:01.493+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:01.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.969 seconds
[2025-05-20T10:31:31.664+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:31.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:31:31.666+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:31:31.665+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:32.125+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:31:32.125+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:31:50.319+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:31:50.310+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from transform import transform_gold_data
  File "/opt/airflow/dags/transform.py", line 6, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:31:50.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:31:50.343+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.683 seconds
[2025-05-20T10:37:48.423+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:37:48.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:37:48.431+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:37:48.427+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:37:53.994+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:37:53.993+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:38:17.913+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:38:17.905+0000] {timeout.py:68} ERROR - Process timed out, PID: 167
[2025-05-20T10:38:17.985+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:38:17.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 27, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 167
[2025-05-20T10:38:17.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:38:18.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.194 seconds
[2025-05-20T10:38:48.929+0000] {processor.py:157} INFO - Started process (PID=230) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:38:48.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:38:48.931+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:38:48.931+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:38:49.518+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:38:49.517+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:39:12.922+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:39:12.915+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from transform import transform_gold_data
  File "/opt/airflow/dags/transform.py", line 6, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:39:12.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:39:12.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 24.066 seconds
[2025-05-20T10:39:43.189+0000] {processor.py:157} INFO - Started process (PID=343) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:39:43.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:39:43.192+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:39:43.192+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:39:43.987+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:39:43.987+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:40:08.666+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:40:08.654+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from transform import transform_gold_data
  File "/opt/airflow/dags/transform.py", line 6, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:40:08.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:40:08.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 25.566 seconds
[2025-05-20T10:40:39.082+0000] {processor.py:157} INFO - Started process (PID=447) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:40:39.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:40:39.086+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:40:39.085+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:40:40.496+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:40:40.495+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:41:00.890+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:41:00.881+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 5, in <module>
    from transform import transform_gold_data
  File "/opt/airflow/dags/transform.py", line 6, in <module>
    HDFS_CLIENT = InsecureClient("http://namenode:9870", user="hadoop")
NameError: name 'InsecureClient' is not defined
[2025-05-20T10:41:00.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:41:00.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.894 seconds
[2025-05-20T10:41:31.289+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:41:31.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:41:31.293+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:41:31.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:41:34.030+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:41:34.029+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:42:40.236+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:42:40.238+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:42:40.239+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:42:40.239+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:42:45.930+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:42:45.929+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:43:10.214+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:43:10.211+0000] {timeout.py:68} ERROR - Process timed out, PID: 168
[2025-05-20T10:43:10.240+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:43:10.220+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 168
[2025-05-20T10:43:10.242+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:43:10.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.124 seconds
[2025-05-20T10:43:40.847+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:43:40.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:43:40.848+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:43:40.848+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:43:42.277+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:43:42.277+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:00.518+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:00.517+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:00.846+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:44:01.263+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.263+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:01.275+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:44:01.377+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.377+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:44:01.390+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.389+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:44:01.399+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.399+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-05-20T10:44:01.400+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.399+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:44:01.401+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.400+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:44:01.417+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.417+0000] {dag.py:2937} INFO - Creating ORM DAG for gold_pipelines
[2025-05-20T10:44:01.431+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:01.430+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:44:01.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.658 seconds
[2025-05-20T10:44:31.801+0000] {processor.py:157} INFO - Started process (PID=387) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:44:31.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:44:31.812+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:31.811+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:44:33.271+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:33.270+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:54.239+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:54.239+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:54.515+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:44:54.650+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:54.650+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:44:54.661+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:44:54.689+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:54.688+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:44:54.715+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:44:54.715+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:44:54.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 22.945 seconds
[2025-05-20T10:45:24.918+0000] {processor.py:157} INFO - Started process (PID=652) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:45:24.924+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:45:24.934+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:45:24.929+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:45:27.826+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:45:27.825+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:45:54.911+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:45:54.905+0000] {timeout.py:68} ERROR - Process timed out, PID: 652
[2025-05-20T10:45:54.927+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:45:54.914+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 652
[2025-05-20T10:45:54.929+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:45:54.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.108 seconds
[2025-05-20T10:46:25.533+0000] {processor.py:157} INFO - Started process (PID=1071) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:46:25.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:46:25.536+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:46:25.536+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:46:28.245+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:46:28.244+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:46:55.527+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:46:55.521+0000] {timeout.py:68} ERROR - Process timed out, PID: 1071
[2025-05-20T10:46:55.558+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:46:55.532+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 1071
[2025-05-20T10:46:55.560+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:46:55.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.134 seconds
[2025-05-20T10:47:26.447+0000] {processor.py:157} INFO - Started process (PID=1362) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:47:26.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:47:26.449+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:26.449+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:47:27.806+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:27.805+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:47:49.556+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:49.556+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:47:50.026+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:47:50.249+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:50.249+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:47:50.259+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:47:50.437+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:50.436+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:47:50.438+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:50.438+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:47:50.460+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:47:50.459+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:47:50.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 24.103 seconds
[2025-05-20T10:48:21.032+0000] {processor.py:157} INFO - Started process (PID=1470) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:48:21.033+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:48:21.034+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:21.034+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:48:22.216+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:22.215+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:48:44.457+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:44.456+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:48:44.659+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:48:44.780+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:44.779+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:48:44.791+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:48:44.863+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:44.862+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:48:44.901+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:48:44.900+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:48:44.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 23.962 seconds
[2025-05-20T10:49:15.583+0000] {processor.py:157} INFO - Started process (PID=1577) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:49:15.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:49:15.586+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:15.585+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:49:16.616+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:16.615+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:49:35.799+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:35.799+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:49:36.132+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:49:36.270+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:36.270+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:49:36.286+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:49:36.315+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:36.314+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:49:36.339+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:49:36.339+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:49:36.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.864 seconds
[2025-05-20T10:50:06.817+0000] {processor.py:157} INFO - Started process (PID=1681) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:50:06.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:50:06.828+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:50:06.826+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:50:10.181+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:50:10.180+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:51:12.404+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:51:12.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:51:12.424+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:51:12.423+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:51:20.115+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:51:20.114+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:51:42.552+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:51:42.546+0000] {timeout.py:68} ERROR - Process timed out, PID: 167
[2025-05-20T10:51:42.581+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:51:42.557+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 167
[2025-05-20T10:51:42.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:51:42.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.326 seconds
[2025-05-20T10:52:13.102+0000] {processor.py:157} INFO - Started process (PID=262) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:52:13.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:52:13.104+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:13.104+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:52:14.290+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:14.290+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:52:35.177+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:35.176+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:52:35.764+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:52:36.120+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:36.120+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:52:36.130+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:52:36.235+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:36.234+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:52:36.236+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:36.235+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:52:36.258+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:52:36.258+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:52:36.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 23.244 seconds
[2025-05-20T10:53:06.634+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:53:06.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:53:06.637+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:06.637+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:53:07.928+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:07.928+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:53:25.440+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:25.440+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:53:25.710+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:53:25.812+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:25.812+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:53:25.821+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:53:25.851+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:25.850+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:53:25.876+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:25.876+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:53:25.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.272 seconds
[2025-05-20T10:53:56.139+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:53:56.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:53:56.141+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:56.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:53:57.183+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:53:57.182+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:54:14.526+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:14.526+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:54:14.747+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:54:14.850+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:14.849+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:54:14.859+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:54:14.885+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:14.885+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:54:14.911+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:14.910+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:54:14.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.850 seconds
[2025-05-20T10:54:45.226+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:54:45.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:54:45.230+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:45.229+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:54:46.233+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:54:46.232+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:55:03.658+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:03.657+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:55:03.881+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:55:03.981+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:03.981+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:55:03.990+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:55:04.017+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:04.016+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:55:04.042+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:04.042+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:55:04.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.892 seconds
[2025-05-20T10:55:34.870+0000] {processor.py:157} INFO - Started process (PID=767) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:55:34.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:55:34.879+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:34.874+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:55:38.140+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:55:38.139+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:56:04.866+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:56:04.862+0000] {timeout.py:68} ERROR - Process timed out, PID: 767
[2025-05-20T10:56:04.881+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:56:04.871+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 767
[2025-05-20T10:56:04.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:56:04.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.121 seconds
[2025-05-20T10:56:35.387+0000] {processor.py:157} INFO - Started process (PID=1272) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:56:35.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:56:35.401+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:56:35.400+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:56:37.610+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:56:37.609+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:57:05.408+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:05.405+0000] {timeout.py:68} ERROR - Process timed out, PID: 1272
[2025-05-20T10:57:05.433+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:05.415+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 1272
[2025-05-20T10:57:05.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:57:05.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.165 seconds
[2025-05-20T10:57:36.143+0000] {processor.py:157} INFO - Started process (PID=1685) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:57:36.144+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:57:36.145+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:36.145+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:57:37.095+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:37.094+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:57:54.244+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:54.244+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:57:54.645+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:57:54.783+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:54.783+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:57:54.795+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:57:54.995+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:54.994+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T10:57:54.996+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:54.996+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:57:55.019+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:57:55.019+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:57:55.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.910 seconds
[2025-05-20T10:58:25.682+0000] {processor.py:157} INFO - Started process (PID=1786) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:58:25.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:58:25.688+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:25.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:58:26.994+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:26.994+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:58:44.967+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:44.966+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:58:45.251+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:58:45.382+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:45.382+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:58:45.394+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:58:45.426+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:45.425+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:58:45.480+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:58:45.480+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:58:45.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.902 seconds
[2025-05-20T10:59:15.786+0000] {processor.py:157} INFO - Started process (PID=1888) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:59:15.789+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:59:15.792+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:15.791+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:59:17.193+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:17.193+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:59:36.262+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:36.262+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:59:36.469+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T10:59:36.565+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:36.565+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T10:59:36.573+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T10:59:36.598+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:36.598+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T10:59:36.621+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:36.621+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T10:59:36.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.923 seconds
[2025-05-20T10:59:50.398+0000] {processor.py:157} INFO - Started process (PID=1988) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T10:59:50.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T10:59:50.401+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:50.401+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T10:59:51.281+0000] {logging_mixin.py:151} INFO - [2025-05-20T10:59:51.280+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:00:12.261+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:12.260+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:00:12.800+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:00:13.113+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:13.111+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:00:13.135+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:00:13.364+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:13.363+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T11:00:13.365+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:13.365+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:00:13.392+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:13.391+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:00:13.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 23.080 seconds
[2025-05-20T11:00:43.720+0000] {processor.py:157} INFO - Started process (PID=2165) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:00:43.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:00:43.724+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:43.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:00:45.406+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:00:45.405+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:01:09.105+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:09.104+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:01:09.576+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:01:09.743+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:09.743+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:01:09.753+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:01:09.798+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:09.797+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:01:09.844+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:09.843+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:01:09.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 26.211 seconds
[2025-05-20T11:01:40.572+0000] {processor.py:157} INFO - Started process (PID=2424) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:01:40.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:01:40.575+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:40.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:01:41.908+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:01:41.906+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:03.769+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:03.768+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:04.011+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:02:04.108+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:04.108+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:04.115+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:02:04.139+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:04.139+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:02:04.161+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:04.160+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:02:04.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 23.671 seconds
[2025-05-20T11:02:34.460+0000] {processor.py:157} INFO - Started process (PID=2591) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:02:34.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:02:34.463+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:34.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:02:35.637+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:35.637+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:54.458+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:54.458+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:54.674+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:02:54.775+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:54.775+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:02:54.783+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:02:54.817+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:54.817+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:02:54.854+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:02:54.854+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:02:54.881+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.429 seconds
[2025-05-20T11:03:04.747+0000] {processor.py:157} INFO - Started process (PID=2689) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:03:04.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:03:04.750+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:04.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:03:05.922+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:05.921+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:03:25.424+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:25.423+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:03:25.665+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:03:25.785+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:25.785+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:03:25.836+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:03:25.992+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:25.991+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T11:03:25.994+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:25.993+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:03:26.067+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:26.067+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:03:26.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.450 seconds
[2025-05-20T11:03:56.380+0000] {processor.py:157} INFO - Started process (PID=2911) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:03:56.389+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:03:56.395+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:56.395+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:03:59.342+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:03:59.341+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:04:26.388+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:04:26.384+0000] {timeout.py:68} ERROR - Process timed out, PID: 2911
[2025-05-20T11:04:26.469+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:04:26.432+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 29, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2911
[2025-05-20T11:04:26.482+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:04:26.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.300 seconds
[2025-05-20T11:04:57.351+0000] {processor.py:157} INFO - Started process (PID=3400) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:04:57.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:04:57.356+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:04:57.355+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:05:02.090+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:05:02.089+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:05:27.388+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:05:27.385+0000] {timeout.py:68} ERROR - Process timed out, PID: 3400
[2025-05-20T11:05:27.422+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:05:27.405+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 4, in <module>
    from extract_gold import extract_gold_data
  File "/opt/airflow/dags/extract_gold.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1822, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.8/subprocess.py", line 1780, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/pipeline.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 3400
[2025-05-20T11:05:27.429+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:05:27.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 30.229 seconds
[2025-05-20T11:05:57.747+0000] {processor.py:157} INFO - Started process (PID=3680) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:05:57.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:05:57.750+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:05:57.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:05:58.900+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:05:58.899+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:06:18.516+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:18.516+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:06:18.734+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:06:18.878+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:18.878+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:06:18.892+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:06:19.020+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:19.019+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T11:06:19.022+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:19.021+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:06:19.047+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:19.047+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:06:19.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.392 seconds
[2025-05-20T11:06:50.048+0000] {processor.py:157} INFO - Started process (PID=3779) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:06:50.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:06:50.056+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:50.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:06:52.198+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:06:52.197+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:07:15.575+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:15.575+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:07:15.909+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:07:16.061+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:16.061+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:07:16.081+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:07:16.125+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:16.124+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:07:16.168+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:16.167+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:07:16.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 26.212 seconds
[2025-05-20T11:07:46.692+0000] {processor.py:157} INFO - Started process (PID=3890) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:07:46.694+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:07:46.696+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:46.695+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:07:47.765+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:07:47.764+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:05.132+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:05.131+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:05.355+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:08:05.466+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:05.466+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:05.479+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:08:05.505+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:05.504+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:08:05.529+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:05.529+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:08:05.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.938 seconds
[2025-05-20T11:08:36.138+0000] {processor.py:157} INFO - Started process (PID=4002) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:08:36.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:08:36.141+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:36.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:08:37.224+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:37.223+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:57.158+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:57.157+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:57.480+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:08:57.593+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:57.592+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:08:57.607+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:08:57.638+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:57.638+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:08:57.675+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:08:57.675+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:08:57.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.579 seconds
[2025-05-20T11:09:27.978+0000] {processor.py:157} INFO - Started process (PID=4104) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:09:27.982+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:09:27.985+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:09:27.984+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:09:29.154+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:09:29.153+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:09:48.245+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103 UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
[2025-05-20T11:09:48.622+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:09:48.622+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:09:48.654+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:09:48.691+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:09:48.690+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:09:48.724+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:09:48.723+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:09:48.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.775 seconds
[2025-05-20T11:10:19.430+0000] {processor.py:157} INFO - Started process (PID=4209) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:10:19.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:10:19.434+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:10:19.434+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:10:20.636+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:10:20.635+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:10:38.722+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:10:38.755+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:10:38.754+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:10:38.783+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:10:38.783+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:10:38.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 19.462 seconds
[2025-05-20T11:11:09.014+0000] {processor.py:157} INFO - Started process (PID=4314) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:11:09.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:11:09.018+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:11:09.017+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:11:10.073+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:11:10.072+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:11:30.079+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:11:30.105+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:11:30.105+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:11:30.129+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:11:30.129+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:11:30.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 21.205 seconds
[2025-05-20T11:12:00.316+0000] {processor.py:157} INFO - Started process (PID=4413) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:12:00.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:12:00.320+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:00.319+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:12:01.258+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:01.258+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:12:19.071+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:12:19.102+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:19.101+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:12:19.124+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:19.124+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:12:19.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 18.833 seconds
[2025-05-20T11:12:49.378+0000] {processor.py:157} INFO - Started process (PID=4524) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:12:49.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:12:49.380+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:49.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:12:50.393+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:12:50.392+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://namenode:9870')>.
[2025-05-20T11:13:09.722+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:13:09.793+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:13:09.792+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:13:09.835+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:13:09.835+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:13:09.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 20.539 seconds
[2025-05-20T11:13:40.594+0000] {processor.py:157} INFO - Started process (PID=4632) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:13:40.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:13:40.597+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:13:40.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:13:40.648+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:13:40.683+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:13:40.683+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:13:40.715+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:13:40.715+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:13:40.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.152 seconds
[2025-05-20T11:14:11.138+0000] {processor.py:157} INFO - Started process (PID=4659) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:11.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:14:11.141+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:11.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:11.203+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:11.244+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:11.244+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:14:11.273+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:11.273+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:14:11.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.173 seconds
[2025-05-20T11:14:15.408+0000] {processor.py:157} INFO - Started process (PID=4664) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:15.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:14:15.410+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:15.410+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:15.459+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:15.574+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:15.574+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T11:14:15.575+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:15.575+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:14:15.602+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:15.602+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:14:15.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.227 seconds
[2025-05-20T11:14:45.673+0000] {processor.py:157} INFO - Started process (PID=4679) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:45.674+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:14:45.675+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:45.675+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:45.716+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:14:45.747+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:45.747+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:14:45.815+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:14:45.815+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:14:45.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.178 seconds
[2025-05-20T11:15:12.502+0000] {processor.py:157} INFO - Started process (PID=4694) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:12.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:15:12.505+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:12.504+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:12.568+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:12.606+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:12.606+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:15:12.639+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:12.639+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:15:12.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.177 seconds
[2025-05-20T11:15:43.052+0000] {processor.py:157} INFO - Started process (PID=4799) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:43.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:15:43.056+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:43.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:43.126+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:43.174+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:43.174+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:15:43.219+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:43.218+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:15:43.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.218 seconds
[2025-05-20T11:15:53.431+0000] {processor.py:157} INFO - Started process (PID=4830) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:53.433+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:15:53.435+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:53.434+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:53.503+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:15:53.744+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:53.743+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:gold_pipelines' as access control is unset.
[2025-05-20T11:15:53.745+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:53.744+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:15:53.796+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:15:53.796+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:15:53.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.436 seconds
[2025-05-20T11:16:24.275+0000] {processor.py:157} INFO - Started process (PID=4874) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:24.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:16:24.279+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:24.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:24.339+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:24.383+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:24.383+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:16:24.415+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:24.415+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:16:24.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.176 seconds
[2025-05-20T11:16:54.580+0000] {processor.py:157} INFO - Started process (PID=4889) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:54.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:16:54.583+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:54.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:54.637+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:16:54.675+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:54.675+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:16:54.707+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:16:54.707+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:16:54.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.160 seconds
[2025-05-20T11:17:25.228+0000] {processor.py:157} INFO - Started process (PID=4904) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:25.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:17:25.231+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:25.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:25.288+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:25.324+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:25.324+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:17:25.355+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:25.354+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:17:25.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.157 seconds
[2025-05-20T11:17:55.520+0000] {processor.py:157} INFO - Started process (PID=4919) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:55.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:17:55.523+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:55.523+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:55.562+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:17:55.598+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:55.598+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:17:55.625+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:17:55.625+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:17:55.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.135 seconds
[2025-05-20T11:18:25.846+0000] {processor.py:157} INFO - Started process (PID=4934) to work on /opt/airflow/dags/pipeline.py
[2025-05-20T11:18:25.848+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-05-20T11:18:25.849+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:18:25.849+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-05-20T11:18:25.907+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gold_pipelines']) retrieved from /opt/airflow/dags/pipeline.py
[2025-05-20T11:18:26.010+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:18:26.009+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-05-20T11:18:26.115+0000] {logging_mixin.py:151} INFO - [2025-05-20T11:18:26.114+0000] {dag.py:3696} INFO - Setting next_dagrun for gold_pipelines to 2025-05-01T00:00:00+00:00, run_after=2025-06-01T00:00:00+00:00
[2025-05-20T11:18:26.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pipeline.py took 0.316 seconds
